version: '2.1'

services:
  master:
    image: shuaicj/spark-master:2.1.1
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3

  slave:
    image: shuaicj/spark-slave:2.1.1
    command: spark://master:7077
    depends_on:
      master:
        condition: service_healthy

  driver:
    image: shuaicj/spark-driver:2.1.1
    volumes:
      - ./sample:/spark/sample
    depends_on:
      master:
        condition: service_healthy
